export const TAREFA_DESCRIPTION_CHANGED = 'TAREFA_DESCRIPTION_CHANGED';
export const TAREFAS_SEARCHED = 'TAREFAS_SEARCHED';
export const TAREFAS_CLEAR = 'TAREFAS_CLEAR';
export const TAREFAS_GET_DATA = 'TAREFAS_GET_DATA';