export const DESCRIPTION_CHANGED = 'CLIENTE_DESCRIPTION_CHANGED';
export const TAREFA_DESCRIPTION_CHANGED = 'TAREFA_DESCRIPTION_CHANGED';
export const TODO_SEARCHED = 'CLIENTE_SEARCHED';
export const TODO_CLEAR = 'CLIENTE_CLEAR';
export const TODO_GET_DATA = 'CLIENTE_GET_DATA';
export const TAREFAS_GET_DATA = 'TAREFAS_GET_DATA';