export const CLIENTE_DESCRIPTION_CHANGED = 'CLIENTE_DESCRIPTION_CHANGED';
export const CLIENTE_SEARCHED = 'CLIENTE_SEARCHED';
export const CLIENTE_CLEAR = 'CLIENTE_CLEAR';
export const CLIENTE_GET_DATA = 'CLIENTE_GET_DATA';