export const RELATORIO_DESCRIPTION_CHANGED = 'RELATORIO_DESCRIPTION_CHANGED';
export const RELATORIO_SEARCHED = 'RELATORIO_SEARCHED';
export const RELATORIO_CLEAR = 'RELATORIO_CLEAR';
export const RELATORIO_GET_DATA = 'RELATORIO_GET_DATA';